// This file was generated by RedwoodJS
import FatalErrorPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/NotFoundPage/NotFoundPage'
import PostEditPostPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}
