// This file was generated by RedwoodJS
import FatalErrorPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/media/tirimescu/Web-Development/Applications/redwood applications/my-redwood-project/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
